version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: DATABASE_USER
      POSTGRES_PASSWORD: DATABASE_PWD
      POSTGRES_DB: DATABASE_NAME
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pg_network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - pg_network

volumes:
  pg_data:

networks:
  pg_network:
    driver: bridge